# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Yuuko
description: A Discord command framework based on Eris.

# Build settings
markdown: kramdown

# List of files to include despite their names beginning with underscores.
#
# This needs to be at the end of the file because the docs build script adds
# entries to this list by echoing them into the end of the file.
include:
- 'docs/v2.0.0/classes/_client_.client.html'
- 'docs/v2.0.0/classes/_command_.command.html'
- 'docs/v2.0.0/interfaces/_client_.clientoauthapplication.html'
- 'docs/v2.0.0/interfaces/_client_.clientoptions.html'
- 'docs/v2.0.0/interfaces/_client_.prefixfunction.html'
- 'docs/v2.0.0/interfaces/_client_.yuukoevents.html'
- 'docs/v2.0.0/interfaces/_command_.commandcontext.html'
- 'docs/v2.0.0/interfaces/_command_.commandprocess.html'
- 'docs/v2.0.0/interfaces/_command_.commandrequirements.html'
- 'docs/v2.0.0/interfaces/_command_.partialcommandcontext.html'
- 'docs/v2.0.0/modules/_client_.html'
- 'docs/v2.0.0/modules/_command_.html'
- 'docs/v2.0.0/modules/_util_.html'
- 'docs/v2.0.0/modules/_yuuko_.html'
- 'docs/v2.0.1/classes/_client_.client.html'
- 'docs/v2.0.1/classes/_command_.command.html'
- 'docs/v2.0.1/interfaces/_client_.clientoauthapplication.html'
- 'docs/v2.0.1/interfaces/_client_.clientoptions.html'
- 'docs/v2.0.1/interfaces/_client_.prefixfunction.html'
- 'docs/v2.0.1/interfaces/_client_.yuukoevents.html'
- 'docs/v2.0.1/interfaces/_command_.commandcontext.html'
- 'docs/v2.0.1/interfaces/_command_.commandprocess.html'
- 'docs/v2.0.1/interfaces/_command_.commandrequirements.html'
- 'docs/v2.0.1/interfaces/_command_.partialcommandcontext.html'
- 'docs/v2.0.1/modules/_client_.html'
- 'docs/v2.0.1/modules/_command_.html'
- 'docs/v2.0.1/modules/_util_.html'
- 'docs/v2.0.1/modules/_yuuko_.html'
- 'docs/v2.0.2/classes/_client_.client.html'
- 'docs/v2.0.2/classes/_command_.command.html'
- 'docs/v2.0.2/interfaces/_client_.clientoauthapplication.html'
- 'docs/v2.0.2/interfaces/_client_.clientoptions.html'
- 'docs/v2.0.2/interfaces/_client_.prefixfunction.html'
- 'docs/v2.0.2/interfaces/_client_.yuukoevents.html'
- 'docs/v2.0.2/interfaces/_command_.commandcontext.html'
- 'docs/v2.0.2/interfaces/_command_.commandprocess.html'
- 'docs/v2.0.2/interfaces/_command_.commandrequirements.html'
- 'docs/v2.0.2/interfaces/_command_.partialcommandcontext.html'
- 'docs/v2.0.2/modules/_client_.html'
- 'docs/v2.0.2/modules/_command_.html'
- 'docs/v2.0.2/modules/_util_.html'
- 'docs/v2.0.2/modules/_yuuko_.html'
